on: push

name: Build XMRig

jobs:
  build_win:
    name: Windows build
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Checkout dependencies
        run: git clone https://github.com/xmrig/xmrig-deps.git
      - name: Build project on Windows
        run: |
          cmake . -G "MinGW Makefiles" -DXMRIG_DEPS=xmrig-deps\gcc\x64
          make -j2
      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows_build
          path: xmrig.exe

  build_linux:
    name: Ubuntu build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build project on Ubuntu
        run: |
          cmake .
          make -j$(nproc)
      - name: Upload Ubuntu build
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_build
          path: xmrig
